### ISSUE TITLE
ccminer source codes? (GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007) #1

### ISSUE THREAD

**Issue by Sniffdog** [nemosminer/ccminer-Alexis78#1]
This was not forked.... so what was the problem with mine then??????

Licensed under the GNU General Public License v3.0 Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

**Comment by nemosminer** [comment]
Source code: https://github.com/nemosminer/ccminer-Alexis78

you need to have a souce code for every ccminer release you add..

**Comment by nemosminer** [comment]
Sorry i am trying to help you.. i properly should of PM you on bitcointalk and let you know
